name = "your-online-bank"
type = "javascript"
account_id = "334ae6e032161bde45cf80ca3465f41d"
workers_dev = true
main = "src/index.ts"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."

[env.production]
name = "your-online-bank-prod"
route = "https://yourdomain.com/*"
zone_id = "YOUR_ZONE_ID"
